services:
  stockmaster:
    image: stockmaster-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5120:5120"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\\SQLEXPRESS;Database=smartstock;User Id=sa;Password=Manyatta2025!;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:5120
    depends_on: []

  smartstockapi:
    image: smartstock-api
    build:
      context: ../SmartStockAPI
      dockerfile: Dockerfile
    ports:
      - "5168:5168"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\\SQLEXPRESS;Database=smartstock;User Id=sa;Password=Manyatta2025!;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:5168
    depends_on: []
