services:
  api:
    build:
      context: "C:/Users/pruoy/source/repos/wpaulruoya/SmartStockAPI"
      dockerfile: Dockerfile
    ports:
      - "5168:5168"
      - "7122:7122"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database,8089;Database=smartstock;User Id=sa;Password=Manyatta2025!;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False
      - ASPNETCORE_URLS=http://+:5168   # 👈 Add this
    depends_on:
      - database

  web:
    build:
      context: "C:/Users/pruoy/source/repos/wpaulruoya/StockMaster"
      dockerfile: Dockerfile
    ports:
      - "5120:5120"
      - "7082:7082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database,8089;Database=smartstock;User Id=sa;Password=Manyatta2025!;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False
      - ASPNETCORE_URLS=http://+:5120   # 👈 Add this
    depends_on:
      - api
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: stockmaster_db
    ports:
      - "8089:1433"
    environment:
      SA_PASSWORD: "Manyatta2025!"
      ACCEPT_EULA: "Y"
