services:
  api:
    build:
      context: "C:/Users/pruoy/source/repos/wpaulruoya/SmartStockAPI"
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=smartstock;User Id=sa;Password=Manyatta;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - database

  web:
    build:
      context: "C:/Users/pruoy/source/repos/wpaulruoya/StockMaster"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=smartstock;User Id=sa;Password=Manyatta;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - api
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: stockmaster_db
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "Manyatta"
      ACCEPT_EULA: "Y"
