version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:5000" # Map host port 8080 to container port 5000 (MVC/API)
      - "8081:5001" # HTTPS port
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=SmartStockDB;User Id=sa;Password=YourStrong!Passw0rd;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
