version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: SmartStockAPI/Dockerfile
    ports:
      - "5001:8080"  # Map host port 5001 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  mvc:
    build:
      context: .
      dockerfile: StockMaster/Dockerfile
    ports:
      - "5002:8081"  # Map host port 5002 to container port 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
