services:
  smartstock-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: smartstock
    restart: always
    environment:
      SA_PASSWORD: "Manyatta2025!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - smartstock_data:/var/opt/mssql

  stockmaster-web:
    build:
      context: C:/Users/pruoy/source/repos/wpaulruoya/StockMaster  # Corrected to reference StockMaster explicitly
      dockerfile: Dockerfile
    container_name: stockmaster-web
    ports:
      - "5120:5120"
      - "7085:7085"
    depends_on:
      - smartstock-db

  stockmaster-api:
    build:
      context: C:/Users/pruoy/source/repos/wpaulruoya/SmartStockAPI  # Corrected to reference SmartStockAPI explicitly
      dockerfile: Dockerfile
    container_name: stockmaster-api
    ports:
      - "5168:5168"
      - "7122:7122"
    depends_on:
      - smartstock-db

volumes:
  smartstock_data:
