services:
  stockmaster:
    image: stockmaster
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5120:5120"   # HTTP
      - "7085:7085"   # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=smartstock;User Id=sa;Password=Manyatta2025!;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1435:1433"  # Maps SQL Server container port 1433 to host 1435
    environment:
      SA_PASSWORD: "Manyatta2025!"
      ACCEPT_EULA: "Y"
    restart: always
